/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// This file provides a simple key-value interface for storing data,
// mapped to structured relational SQL tables.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

export function resolveTable(key: string): { table: string; id: string } {
  if (key.startsWith("profile:")) {
    return { table: "profiles", id: key.substring("profile:".length) };
  }
  if (key.startsWith("contracts:")) {
    return { table: "contracts", id: key.substring("contracts:".length) };
  }
  if (key.startsWith("claims:")) {
    return { table: "claims", id: key.substring("claims:".length) };
  }
  if (key.startsWith("payments:")) {
    return { table: "payments", id: key.substring("payments:".length) };
  }
  if (key.startsWith("beneficiaries:")) {
    return { table: "beneficiaries", id: key.substring("beneficiaries:".length) };
  }
  if (key.startsWith("settings:")) {
    return { table: "settings", id: key.substring("settings:".length) };
  }
  if (key.startsWith("notifications:")) {
    return { table: "notifications", id: key.substring("notifications:".length) };
  }
  if (key.startsWith("messages:")) {
    return { table: "messages", id: key.substring("messages:".length) };
  }
  if (key.startsWith("kyc:")) {
    return { table: "kyc", id: key.substring("kyc:".length) };
  }
  if (key.startsWith("audit:")) {
    return { table: "user_audits", id: key.substring("audit:".length) };
  }
  return { table: "system_kv", id: key };
}

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  
  if (key.startsWith("profile:")) {
    const uid = key.substring("profile:".length);
    const dbRow = mapProfileToDb({ ...value, id: uid });
    const { error } = await supabase.from("profiles").upsert(dbRow);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("contracts:")) {
    const uid = key.substring("contracts:".length);
    const list = Array.isArray(value) ? value : [];
    const dbRows = list.map(c => mapContractToDb({ ...c, userId: uid }));
    await syncArray(supabase, "contracts", uid, dbRows);
  } else if (key.startsWith("claims:")) {
    const uid = key.substring("claims:".length);
    const list = Array.isArray(value) ? value : [];
    const dbRows = list.map(c => mapClaimToDb({ ...c, userId: uid }));
    await syncArray(supabase, "claims", uid, dbRows);
  } else if (key.startsWith("payments:")) {
    const uid = key.substring("payments:".length);
    const list = Array.isArray(value) ? value : [];
    const dbRows = list.map(p => mapPaymentToDb({ ...p, userId: uid }));
    await syncArray(supabase, "payments", uid, dbRows);
  } else if (key.startsWith("beneficiaries:")) {
    const uid = key.substring("beneficiaries:".length);
    const list = Array.isArray(value) ? value : [];
    const dbRows = list.map(b => mapBeneficiaryToDb({ ...b, userId: uid }));
    await syncArray(supabase, "beneficiaries", uid, dbRows);
  } else if (key.startsWith("settings:")) {
    const uid = key.substring("settings:".length);
    const dbRow = mapSettingsToDb({ ...value, userId: uid });
    const { error } = await supabase.from("settings").upsert(dbRow);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("notifications:")) {
    const uid = key.substring("notifications:".length);
    const list = Array.isArray(value) ? value : [];
    const dbRows = list.map(n => mapNotificationToDb({ ...n, userId: uid }));
    await syncArray(supabase, "notifications", uid, dbRows);
  } else if (key.startsWith("messages:")) {
    const uid = key.substring("messages:".length);
    const list = Array.isArray(value) ? value : [];
    const dbRows = list.map(m => mapMessageToDb({ ...m, userId: uid }));
    await syncArray(supabase, "messages", uid, dbRows);
  } else if (key.startsWith("kyc:")) {
    const uid = key.substring("kyc:".length);
    const list: any[] = [];
    if (value?.current) list.push({ ...value.current, userId: uid });
    if (Array.isArray(value?.history)) {
      list.push(...value.history.map((h: any) => ({ ...h, userId: uid })));
    }
    const dbRows = list.map(k => mapKycToDb(k));
    await syncArray(supabase, "kyc", uid, dbRows);
  } else if (key.startsWith("audit:")) {
    const uid = key.substring("audit:".length);
    const list = Array.isArray(value) ? value : [];
    const dbRows = list.map(a => mapAuditToDb({ ...a, userId: uid }));
    await syncArray(supabase, "user_audits", uid, dbRows);
  } else {
    const { error } = await supabase.from("system_kv").upsert({
      id: key,
      value
    });
    if (error) throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  
  if (key.startsWith("profile:")) {
    const uid = key.substring("profile:".length);
    const { data, error } = await supabase.from("profiles").select("*").eq("id", uid).maybeSingle();
    if (error) throw new Error(error.message);
    return mapProfileFromDb(data);
  } else if (key.startsWith("contracts:")) {
    const uid = key.substring("contracts:".length);
    const { data, error } = await supabase.from("contracts").select("*").eq("user_id", uid);
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapContractFromDb);
  } else if (key.startsWith("claims:")) {
    const uid = key.substring("claims:".length);
    const { data, error } = await supabase.from("claims").select("*").eq("user_id", uid);
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapClaimFromDb);
  } else if (key.startsWith("payments:")) {
    const uid = key.substring("payments:".length);
    const { data, error } = await supabase.from("payments").select("*").eq("user_id", uid);
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapPaymentFromDb);
  } else if (key.startsWith("beneficiaries:")) {
    const uid = key.substring("beneficiaries:".length);
    const { data, error } = await supabase.from("beneficiaries").select("*").eq("user_id", uid);
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapBeneficiaryFromDb);
  } else if (key.startsWith("settings:")) {
    const uid = key.substring("settings:".length);
    const { data, error } = await supabase.from("settings").select("*").eq("user_id", uid).maybeSingle();
    if (error) throw new Error(error.message);
    return mapSettingsFromDb(data);
  } else if (key.startsWith("notifications:")) {
    const uid = key.substring("notifications:".length);
    const { data, error } = await supabase.from("notifications").select("*").eq("user_id", uid);
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapNotificationFromDb);
  } else if (key.startsWith("messages:")) {
    const uid = key.substring("messages:".length);
    const { data, error } = await supabase.from("messages").select("*").eq("user_id", uid);
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapMessageFromDb);
  } else if (key.startsWith("kyc:")) {
    const uid = key.substring("kyc:".length);
    const { data, error } = await supabase.from("kyc").select("*").eq("user_id", uid);
    if (error) throw new Error(error.message);
    const list = (data ?? []).map(mapKycFromDb);
    const current = list.find((k: any) => k.status === "pending") ?? null;
    const history = list.filter((k: any) => k.status !== "pending");
    return { current, history };
  } else if (key.startsWith("audit:")) {
    const uid = key.substring("audit:".length);
    const { data, error } = await supabase.from("user_audits").select("*").eq("user_id", uid);
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapAuditFromDb);
  } else {
    const { data, error } = await supabase.from("system_kv").select("value").eq("id", key).maybeSingle();
    if (error) throw new Error(error.message);
    return data?.value;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  
  if (key.startsWith("profile:")) {
    const uid = key.substring("profile:".length);
    const { error } = await supabase.from("profiles").delete().eq("id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("contracts:")) {
    const uid = key.substring("contracts:".length);
    const { error } = await supabase.from("contracts").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("claims:")) {
    const uid = key.substring("claims:".length);
    const { error } = await supabase.from("claims").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("payments:")) {
    const uid = key.substring("payments:".length);
    const { error } = await supabase.from("payments").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("beneficiaries:")) {
    const uid = key.substring("beneficiaries:".length);
    const { error } = await supabase.from("beneficiaries").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("settings:")) {
    const uid = key.substring("settings:".length);
    const { error } = await supabase.from("settings").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("notifications:")) {
    const uid = key.substring("notifications:".length);
    const { error } = await supabase.from("notifications").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("messages:")) {
    const uid = key.substring("messages:".length);
    const { error } = await supabase.from("messages").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("kyc:")) {
    const uid = key.substring("kyc:".length);
    const { error } = await supabase.from("kyc").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else if (key.startsWith("audit:")) {
    const uid = key.substring("audit:".length);
    const { error } = await supabase.from("user_audits").delete().eq("user_id", uid);
    if (error) throw new Error(error.message);
  } else {
    const { error } = await supabase.from("system_kv").delete().eq("id", key);
    if (error) throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  await Promise.all(keys.map((k, i) => set(k, values[i])));
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  return Promise.all(keys.map(k => get(k)));
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  await Promise.all(keys.map(k => del(k)));
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  if (prefix.startsWith("profile:")) {
    const { data, error } = await supabase.from("profiles").select("*");
    if (error) throw new Error(error.message);
    return (data ?? []).map(mapProfileFromDb);
  }
  if (prefix.startsWith("contracts:")) {
    const { data, error } = await supabase.from("contracts").select("*");
    if (error) throw new Error(error.message);
    const groups: Record<string, any[]> = {};
    for (const row of data ?? []) {
      const c = mapContractFromDb(row);
      if (!groups[row.user_id]) groups[row.user_id] = [];
      groups[row.user_id].push(c);
    }
    return Object.values(groups);
  }
  if (prefix.startsWith("claims:")) {
    const { data, error } = await supabase.from("claims").select("*");
    if (error) throw new Error(error.message);
    const groups: Record<string, any[]> = {};
    for (const row of data ?? []) {
      const cl = mapClaimFromDb(row);
      if (!groups[row.user_id]) groups[row.user_id] = [];
      groups[row.user_id].push(cl);
    }
    return Object.values(groups);
  }
  if (prefix.startsWith("payments:")) {
    const { data, error } = await supabase.from("payments").select("*");
    if (error) throw new Error(error.message);
    const groups: Record<string, any[]> = {};
    for (const row of data ?? []) {
      const p = mapPaymentFromDb(row);
      if (!groups[row.user_id]) groups[row.user_id] = [];
      groups[row.user_id].push(p);
    }
    return Object.values(groups);
  }
  if (prefix.startsWith("kyc:")) {
    const { data, error } = await supabase.from("kyc").select("*");
    if (error) throw new Error(error.message);
    const groups: Record<string, any[]> = {};
    for (const row of data ?? []) {
      const k = mapKycFromDb(row);
      if (!groups[row.user_id]) groups[row.user_id] = [];
      groups[row.user_id].push(k);
    }
    return Object.keys(groups).map(uid => {
      const list = groups[uid];
      const current = list.find((k: any) => k.status === "pending") ?? null;
      const history = list.filter((k: any) => k.status !== "pending");
      return { current, history };
    });
  }
  if (prefix.startsWith("agent:presence:")) {
    const { data, error } = await supabase.from("system_kv").select("value").like("id", "agent:presence:%");
    if (error) throw new Error(error.message);
    return data?.map((d: any) => d.value) ?? [];
  }
  
  const { data, error } = await supabase.from("system_kv").select("value").like("id", prefix + "%");
  if (error) throw new Error(error.message);
  return data?.map((d: any) => d.value) ?? [];
};

// Generic array sync helper to prevent duplicate/orphaned records on array updates.
async function syncArray(supabase: any, table: string, userId: string, dbRows: any[]) {
  const newIds = dbRows.map(r => r.id).filter(Boolean);
  let delQuery = supabase.from(table).delete().eq("user_id", userId);
  if (newIds.length > 0) {
    delQuery = delQuery.not("id", "in", `(${newIds.map(id => `"${id}"`).join(",")})`);
  }
  const { error: delErr } = await delQuery;
  if (delErr) throw new Error(delErr.message);

  if (dbRows.length > 0) {
    const { error: upsertErr } = await supabase.from(table).upsert(dbRows);
    if (upsertErr) throw new Error(upsertErr.message);
  }
}

// ============================================================
// Mappers (JS Object <-> PostgreSQL columns)
// ============================================================

function mapProfileToDb(js: any): any {
  return {
    id: js.id,
    email: js.email,
    name: js.name,
    phone: js.phone,
    member_number: js.memberNumber,
    profile_type: js.type,
    sous_profil: js.sousProfil,
    first_name: js.firstName,
    last_name: js.lastName,
    gender: js.gender,
    birth_date: js.birthDate,
    birth_place: js.birthPlace,
    nationality: js.nationality,
    address: js.address,
    profession: js.profession,
    activite: js.activite,
    secteur: js.secteur,
    entreprise: js.entreprise,
    statut_pro: js.statutPro,
    company_name: js.companyName,
    ifu: js.ifu,
    id_type: js.idType,
    id_number: js.idNumber,
    country: js.country,
    country_dial: js.countryDial,
    department: js.department,
    city: js.city,
    quartier: js.quartier,
    couverture: js.couverture,
    couverture_autre: js.couvertureAutre,
    formule: js.formule,
    documents_declares: js.documentsDeclares,
    document_autre: js.documentAutre,
    enrolled_by: js.enrolledBy,
    enrolled_by_uid: js.enrolledByUid,
    enrolled_at: js.enrolledAt,
    enrolled_source: js.enrolledSource,
    kyc_verified: js.kycVerified,
    card_active: js.cardActive,
    card_issued_at: js.cardIssuedAt,
    created_at: js.createdAt
  };
}

function mapProfileFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    email: row.email,
    name: row.name,
    phone: row.phone,
    memberNumber: row.member_number,
    type: row.profile_type,
    sousProfil: row.sous_profil,
    firstName: row.first_name,
    lastName: row.last_name,
    gender: row.gender,
    birthDate: row.birth_date,
    birthPlace: row.birth_place,
    nationality: row.nationality,
    address: row.address,
    profession: row.profession,
    activite: row.activite,
    secteur: row.secteur,
    entreprise: row.entreprise,
    statutPro: row.statut_pro,
    companyName: row.company_name,
    ifu: row.ifu,
    idType: row.id_type,
    idNumber: row.id_number,
    country: row.country,
    countryDial: row.country_dial,
    department: row.department,
    city: row.city,
    quartier: row.quartier,
    couverture: row.couverture,
    couvertureAutre: row.couverture_autre,
    formule: row.formule,
    documentsDeclares: row.documents_declares,
    documentAutre: row.document_autre,
    enrolledBy: row.enrolled_by,
    enrolledByUid: row.enrolled_by_uid,
    enrolledAt: row.enrolled_at,
    enrolledSource: row.enrolled_source,
    kycVerified: row.kyc_verified,
    cardActive: row.card_active,
    cardIssuedAt: row.card_issued_at,
    createdAt: row.created_at
  };
}

function mapContractToDb(js: any): any {
  return {
    id: js.id,
    user_id: js.userId,
    product: js.product,
    premium: js.premium,
    frequency: js.frequency,
    status: js.status,
    start_date: js.startDate,
    end_date: js.endDate,
    subscribed_by: js.subscribedBy,
    subscribed_by_name: js.subscribedByName,
    next_billing_date: js.nextBillingDate,
    pending_renewal_payment_id: js.pendingRenewalPaymentId,
    pending_renewal_at: js.pendingRenewalAt,
    suspended_at: js.suspendedAt,
    suspended_reason: js.suspendedReason,
    last_paid_at: js.lastPaidAt,
    renewal_notice_sent: js.renewalNoticeSent,
    created_at: js.createdAt,
    updated_at: js.updatedAt
  };
}

function mapContractFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id,
    product: row.product,
    premium: row.premium ? Number(row.premium) : null,
    frequency: row.frequency,
    status: row.status,
    startDate: row.start_date,
    endDate: row.end_date,
    subscribedBy: row.subscribed_by,
    subscribedByName: row.subscribed_by_name,
    nextBillingDate: row.next_billing_date,
    pendingRenewalPaymentId: row.pending_renewal_payment_id,
    pendingRenewalAt: row.pending_renewal_at,
    suspendedAt: row.suspended_at,
    suspendedReason: row.suspended_reason,
    lastPaidAt: row.last_paid_at,
    renewalNoticeSent: row.renewal_notice_sent,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

function mapClaimToDb(js: any): any {
  return {
    id: js.id,
    user_id: js.userId,
    contract_id: js.contractId,
    type: js.type,
    description: js.description,
    amount: js.amount,
    status: js.status,
    decided_by: js.decidedBy,
    decided_by_matricule: js.decidedByMatricule,
    decided_at: js.decidedAt,
    admin_note: js.adminNote,
    assigned_to: js.assignedTo,
    assigned_at: js.assignedAt,
    assigned_by: js.assignedBy,
    beneficiary: js.beneficiary,
    beneficiary_id: js.beneficiaryId,
    attachments: js.attachments,
    created_at: js.createdAt,
    updated_at: js.updatedAt
  };
}

function mapClaimFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id,
    contractId: row.contract_id,
    type: row.type,
    description: row.description,
    amount: row.amount ? Number(row.amount) : null,
    status: row.status,
    decidedBy: row.decided_by,
    decidedByMatricule: row.decided_by_matricule,
    decidedAt: row.decided_at,
    adminNote: row.admin_note,
    assignedTo: row.assigned_to,
    assignedAt: row.assigned_at,
    assignedBy: row.assigned_by,
    beneficiary: row.beneficiary,
    beneficiaryId: row.beneficiary_id,
    attachments: row.attachments,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

function mapPaymentToDb(js: any): any {
  return {
    id: js.id,
    user_id: js.userId,
    contract_id: js.contractId,
    amount: js.amount,
    method: js.method,
    purpose: js.purpose,
    status: js.status,
    collected_by: js.collectedBy,
    created_at: js.createdAt,
    updated_at: js.updatedAt
  };
}

function mapPaymentFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id,
    contractId: row.contract_id,
    amount: row.amount ? Number(row.amount) : 0,
    method: row.method,
    purpose: row.purpose,
    status: row.status,
    collectedBy: row.collected_by,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

function mapBeneficiaryToDb(js: any): any {
  return {
    id: js.id,
    user_id: js.userId,
    name: js.name,
    relation: js.relation,
    birth_date: js.birthDate,
    source: js.source,
    created_at: js.createdAt,
    updated_at: js.updatedAt
  };
}

function mapBeneficiaryFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id,
    name: row.name,
    relation: row.relation,
    birthDate: row.birth_date,
    source: row.source,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

function mapSettingsToDb(js: any): any {
  return {
    user_id: js.userId,
    lang: js.lang,
    notify_sms: js.notifySms,
    notify_email: js.notifyEmail
  };
}

function mapSettingsFromDb(row: any): any {
  if (!row) return null;
  return {
    userId: row.user_id,
    lang: row.lang,
    notifySms: row.notify_sms,
    notifyEmail: row.notify_email
  };
}

function mapNotificationToDb(js: any): any {
  return {
    id: js.id,
    user_id: js.userId,
    title: js.title,
    body: js.body,
    type: js.type,
    read: js.read,
    to_path: js.to,
    created_at: js.createdAt
  };
}

function mapNotificationFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id,
    title: row.title,
    body: row.body,
    type: row.type,
    read: row.read,
    to: row.to_path,
    createdAt: row.created_at
  };
}

function mapMessageToDb(js: any): any {
  return {
    id: js.id,
    user_id: js.userId,
    content: js.content,
    reply_to_id: js.replyToId,
    author: js.author,
    attachment: js.attachment,
    created_at: js.createdAt
  };
}

function mapMessageFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id,
    content: row.content,
    replyToId: row.reply_to_id,
    author: row.author,
    attachment: row.attachment,
    createdAt: row.created_at
  };
}

function mapKycToDb(js: any): any {
  return {
    id: js.id,
    user_id: js.userId,
    type: js.type,
    fields: js.fields,
    documents: js.documents,
    status: js.status,
    decided_by: js.decidedBy,
    decided_at: js.decidedAt,
    admin_note: js.adminNote,
    created_at: js.createdAt
  };
}

function mapKycFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id,
    type: row.type,
    fields: row.fields,
    documents: row.documents,
    status: row.status,
    decidedBy: row.decided_by,
    decidedAt: row.decided_at,
    adminNote: row.admin_note,
    createdAt: row.created_at
  };
}

function mapAuditToDb(js: any): any {
  return {
    id: js.id,
    user_id: js.userId,
    action: js.action,
    meta: js.meta,
    created_at: js.at
  };
}

function mapAuditFromDb(row: any): any {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id,
    action: row.action,
    meta: row.meta,
    at: row.created_at
  };
}