/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// This file provides a simple key-value interface for storing data,
// mapped to the single unique table kv_store_752d1a39 to align with index.tsx.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

export function resolveTable(key: string): { table: string; id: string } {
  return { table: "kv_store_752d1a39", id: key };
}

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_752d1a39").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_752d1a39").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_752d1a39").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client();
  const items = keys.map((key, i) => ({ key, value: values[i] }));
  const { error } = await supabase.from("kv_store_752d1a39").upsert(items);
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_752d1a39").select("key, value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  const results = new Array(keys.length);
  const keyToOrder = Object.fromEntries(keys.map((k, i) => [k, i]));
  if (data) {
    for (const item of data) {
      const index = keyToOrder[item.key];
      if (index !== undefined) {
        results[index] = item.value;
      }
    }
  }
  return results.filter((v) => v !== undefined);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_752d1a39").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_752d1a39").select("value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};