/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// This file provides a simple key-value interface for storing data,
// mapped to separate tables depending on the key prefix to avoid a single-table bottleneck.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

export function resolveTable(key: string): { table: string; id: string } {
  if (key.startsWith("profile:")) {
    return { table: "profiles", id: key.substring("profile:".length) };
  }
  if (key.startsWith("contracts:")) {
    return { table: "contracts", id: key.substring("contracts:".length) };
  }
  if (key.startsWith("claims:")) {
    return { table: "claims", id: key.substring("claims:".length) };
  }
  if (key.startsWith("payments:")) {
    return { table: "payments", id: key.substring("payments:".length) };
  }
  if (key.startsWith("beneficiaries:")) {
    return { table: "beneficiaries", id: key.substring("beneficiaries:".length) };
  }
  if (key.startsWith("documents:")) {
    return { table: "documents", id: key.substring("documents:".length) };
  }
  if (key.startsWith("settings:")) {
    return { table: "settings", id: key.substring("settings:".length) };
  }
  if (key.startsWith("notifications:")) {
    return { table: "notifications", id: key.substring("notifications:".length) };
  }
  if (key.startsWith("messages:")) {
    return { table: "messages", id: key.substring("messages:".length) };
  }
  if (key.startsWith("kyc:")) {
    return { table: "kyc", id: key.substring("kyc:".length) };
  }
  if (key.startsWith("audit:")) {
    return { table: "user_audits", id: key.substring("audit:".length) };
  }
  return { table: "system_kv", id: key };
}

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  const { table, id } = resolveTable(key);
  const { error } = await supabase.from(table).upsert({
    id,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  const { table, id } = resolveTable(key);
  const { data, error } = await supabase.from(table).select("value").eq("id", id).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { table, id } = resolveTable(key);
  const { error } = await supabase.from(table).delete().eq("id", id);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client();
  const groups: Record<string, { id: string; value: any }[]> = {};
  for (let i = 0; i < keys.length; i++) {
    const { table, id } = resolveTable(keys[i]);
    if (!groups[table]) groups[table] = [];
    groups[table].push({ id, value: values[i] });
  }
  for (const [table, items] of Object.entries(groups)) {
    const { error } = await supabase.from(table).upsert(items);
    if (error) {
      throw new Error(error.message);
    }
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client();
  const groups: Record<string, string[]> = {};
  const keyToOrder: Record<string, number> = {};
  for (let i = 0; i < keys.length; i++) {
    const { table, id } = resolveTable(keys[i]);
    if (!groups[table]) groups[table] = [];
    groups[table].push(id);
    keyToOrder[`${table}:${id}`] = i;
  }
  
  const results = new Array(keys.length);
  for (const [table, ids] of Object.entries(groups)) {
    const { data, error } = await supabase.from(table).select("id, value").in("id", ids);
    if (error) {
      throw new Error(error.message);
    }
    if (data) {
      for (const item of data) {
        const index = keyToOrder[`${table}:${item.id}`];
        if (index !== undefined) {
          results[index] = item.value;
        }
      }
    }
  }
  return results.filter((v) => v !== undefined);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const groups: Record<string, string[]> = {};
  for (const key of keys) {
    const { table, id } = resolveTable(key);
    if (!groups[table]) groups[table] = [];
    groups[table].push(id);
  }
  for (const [table, ids] of Object.entries(groups)) {
    const { error } = await supabase.from(table).delete().in("id", ids);
    if (error) {
      throw new Error(error.message);
    }
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { table, id } = resolveTable(prefix);
  let query = supabase.from(table).select("value");
  if (id) {
    query = query.like("id", id + "%");
  }
  const { data, error } = await query;
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};