/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "yeisckavsutzmmuafsbk"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaXNja2F2c3V0em1tdWFmc2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNDg0MjgsImV4cCI6MjA5NTYyNDQyOH0.ixMZDxC6jlVZtwDDEAOWUp-f8ydqU7BoFgh8DruxdPs"
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`